name: Push to Hugging Face Space

on:
  push:
    branches:
      - main
      - "*"  # Toutes les branches si tu veux pousser depuis autre chose que main

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Set up Git identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Add Hugging Face remote
      run: |
        git remote add hf https://huggingface.co/spaces/SteruBaratte/IA-juridique-2
        git fetch hf || true

    - name: Force push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://hf:${HF_TOKEN}@huggingface.co/spaces/SteruBaratte/IA-juridique-2 HEAD:main --force
